# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adunits', '0002_auto_20160908_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='name',
            field=models.CharField(default='name', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
