# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-12 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adunits', '0005_auto_20170110_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='endbody_source',
            field=models.TextField(blank=True, help_text='Commonly scripts are needed before </body>', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='header_source',
            field=models.TextField(blank=True, help_text='Commonly, scripts are needed between <head></head>', null=True),
        ),
    ]
